# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 14:05
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Wallpaper'),
        ),
    ]
